theme: jekyll-theme-minimal
title: Ben Evans
description: Senior Computational Research Support Analyst at the [Yale Center for Research Computing](https://research.computing.yale.edu/)

google_analytics: UA-175031839-1
