theme: jekyll-theme-minimal
title: Ben Evans
description: Senior Computational Research Support Analyst at the Yale Center for Research Computing

google_analytics: UA-175031839-1

navigation:
  - title: CV
    url: CV_Benjamin_Robert_Evans.pdf
